export const DEFAULT_CAREER_GOAL = "Frontend Developer";

export const careerGoalOptions = [
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "MERN Stack Developer",
  "Java Developer",
  "Data Analyst",
  "AI/ML Engineer",
  "DevOps Engineer",
];

export const goalData = {
  "Frontend Developer": {
    roadmap: [
      "HTML and CSS fundamentals",
      "JavaScript basics and ES6+",
      "DOM manipulation",
      "React.js fundamentals",
      "React Hooks",
      "Routing with React Router",
      "API integration",
      "State management",
      "Tailwind CSS",
      "Build frontend projects",
      "Deploy projects",
    ],
    skills: [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "Tailwind CSS",
      "GitHub",
      "API Integration",
      "Responsive Design",
    ],
    interviewTopics: [
      "JavaScript fundamentals",
      "Closures and hoisting",
      "Event loop",
      "DOM manipulation",
      "React components",
      "Props vs state",
      "useState and useEffect",
      "React Router",
      "API calls",
      "Performance optimization",
    ],
    projects: [
      "Portfolio Website",
      "Weather App",
      "Task Manager",
      "E-commerce Product Page",
      "Admin Dashboard UI",
      "API-based React App",
    ],
    dailyTasks: [
      "Revise one JavaScript concept",
      "Build one React component",
      "Practice 5 frontend interview questions",
      "Improve one portfolio section",
      "Push code to GitHub",
    ],
    resumeTips: [
      "Add deployed project links",
      "Mention React and JavaScript clearly",
      "Add GitHub links",
      "Include responsive UI experience",
      "Show API integration projects",
      "Add measurable project impact",
    ],
    completedRoadmapSteps: 4,
    completedTaskCount: 2,
    confidence: "Growing",
    practicedQuestions: 8,
    resumeScore: 84,
    atsFriendly: "Good",
    missingSections: ["Project outcomes", "Case study highlights"],
    interviewSuggestion: "Rehearse React hooks, rendering flow, and API loading states.",
    resumeSuggestion: "Show shipped interfaces, measurable UX impact, and live project links.",
  },
  "Backend Developer": {
    roadmap: [
      "Programming and problem-solving foundations",
      "Node.js runtime and modules",
      "Express.js fundamentals",
      "REST API design",
      "Authentication and authorization",
      "SQL and NoSQL databases",
      "Caching and performance",
      "Error handling and logging",
      "Testing backend services",
      "Deployment and monitoring",
      "Build production-ready APIs",
    ],
    skills: [
      "Node.js",
      "Express.js",
      "REST APIs",
      "MongoDB",
      "SQL",
      "Authentication",
      "Postman",
      "System Design Basics",
    ],
    interviewTopics: [
      "REST principles",
      "HTTP methods and status codes",
      "Authentication vs authorization",
      "Middleware flow",
      "Database indexing",
      "SQL joins",
      "Caching strategies",
      "Error handling",
      "Rate limiting",
      "Scalability basics",
    ],
    projects: [
      "Authentication Service API",
      "Blog Backend",
      "Inventory Management API",
      "URL Shortener Service",
      "Realtime Notification Backend",
      "Job Portal Backend",
    ],
    dailyTasks: [
      "Revise one API design concept",
      "Implement one Express endpoint",
      "Practice 5 backend interview questions",
      "Optimize one database query",
      "Document one service in Postman",
    ],
    resumeTips: [
      "Highlight API performance improvements",
      "Mention authentication and security work",
      "Show database schema design experience",
      "Add backend deployment links or docs",
      "Quantify request handling or latency gains",
      "Include testing or monitoring experience",
    ],
    completedRoadmapSteps: 4,
    completedTaskCount: 2,
    confidence: "Steady",
    practicedQuestions: 7,
    resumeScore: 83,
    atsFriendly: "Strong",
    missingSections: ["Performance metrics", "Testing coverage"],
    interviewSuggestion: "Prepare clean explanations for APIs, databases, and auth flows.",
    resumeSuggestion: "Call out scalable API work, security decisions, and query optimization.",
  },
  "Full Stack Developer": {
    roadmap: [
      "HTML, CSS, and JavaScript fundamentals",
      "React frontend development",
      "Node.js and Express backend",
      "Database design and CRUD operations",
      "Authentication flows",
      "State management",
      "API integration and error handling",
      "Testing frontend and backend",
      "Deployment workflows",
      "System design basics",
      "Build end-to-end products",
    ],
    skills: [
      "JavaScript",
      "React",
      "Node.js",
      "Express.js",
      "MongoDB",
      "REST APIs",
      "GitHub",
      "Deployment",
    ],
    interviewTopics: [
      "Frontend-backend architecture",
      "REST APIs",
      "Authentication flow",
      "Component lifecycle",
      "State management",
      "Database relationships",
      "Error handling",
      "Deployment pipeline",
      "Performance tuning",
      "Project tradeoffs",
    ],
    projects: [
      "Full Stack Task Manager",
      "E-learning Platform",
      "Job Application Tracker",
      "Team Collaboration Tool",
      "Expense Management App",
      "Recruitment Dashboard",
    ],
    dailyTasks: [
      "Revise one frontend concept",
      "Build one API or backend feature",
      "Practice 5 full stack interview questions",
      "Improve one end-to-end project flow",
      "Push one meaningful commit",
    ],
    resumeTips: [
      "Show both frontend and backend ownership",
      "Add deployed full stack project links",
      "Mention API and database design clearly",
      "Highlight authentication or dashboard features",
      "Include GitHub repos with clean README files",
      "Quantify user or business impact",
    ],
    completedRoadmapSteps: 5,
    completedTaskCount: 2,
    confidence: "Ready",
    practicedQuestions: 9,
    resumeScore: 86,
    atsFriendly: "Strong",
    missingSections: ["Architecture notes", "User impact metrics"],
    interviewSuggestion: "Practice explaining how your frontend and backend connect in real apps.",
    resumeSuggestion: "Lead with deployed end-to-end builds that prove product ownership.",
  },
  "MERN Stack Developer": {
    roadmap: [
      "JavaScript and ES6+ fundamentals",
      "React component architecture",
      "Node.js and Express fundamentals",
      "MongoDB schema design",
      "Authentication with JWT",
      "State management in React",
      "Full stack CRUD applications",
      "File upload and cloud storage",
      "Testing MERN applications",
      "Deployment on modern platforms",
      "Build scalable MERN products",
    ],
    skills: [
      "MongoDB",
      "Express.js",
      "React",
      "Node.js",
      "JWT Auth",
      "Redux or Context API",
      "API Integration",
      "Cloud Deployment",
    ],
    interviewTopics: [
      "MERN architecture",
      "MongoDB aggregation basics",
      "Express middleware",
      "JWT authentication",
      "React hooks",
      "Context vs Redux",
      "REST APIs",
      "CRUD optimization",
      "Error handling",
      "Deployment strategies",
    ],
    projects: [
      "MERN Blog Platform",
      "E-commerce Store",
      "Learning Management System",
      "Social Feed App",
      "Recruitment Tracker",
      "CRM Dashboard",
    ],
    dailyTasks: [
      "Revise one MERN concept",
      "Build one reusable React view",
      "Practice 5 MERN interview questions",
      "Refine one MongoDB query",
      "Deploy or update one project module",
    ],
    resumeTips: [
      "Mention full CRUD application experience",
      "Add JWT authentication work",
      "Show MongoDB schema design decisions",
      "Link deployed MERN projects",
      "Highlight dashboard and admin features",
      "Quantify performance or usage improvements",
    ],
    completedRoadmapSteps: 5,
    completedTaskCount: 2,
    confidence: "Ready",
    practicedQuestions: 10,
    resumeScore: 87,
    atsFriendly: "Strong",
    missingSections: ["Deployment details", "Scalability examples"],
    interviewSuggestion: "Get fluent at discussing auth, MongoDB design, and React state flow.",
    resumeSuggestion: "Show complete MERN ownership from schema design to deployed UI.",
  },
  "Java Developer": {
    roadmap: [
      "Core Java syntax and OOP",
      "Collections framework",
      "Exception handling",
      "Multithreading basics",
      "JDBC and database interaction",
      "Spring and Spring Boot fundamentals",
      "REST API development",
      "JPA and Hibernate",
      "Unit testing with JUnit",
      "DSA with Java",
      "Build enterprise-style services",
    ],
    skills: [
      "Core Java",
      "OOP",
      "Spring Boot",
      "Hibernate",
      "MySQL",
      "REST APIs",
      "JUnit",
      "DSA",
    ],
    interviewTopics: [
      "OOP principles",
      "String vs StringBuilder",
      "Collections internals",
      "Exception handling",
      "Multithreading",
      "Spring Boot annotations",
      "Dependency injection",
      "JPA lifecycle",
      "SQL joins",
      "Java memory model basics",
    ],
    projects: [
      "Library Management System",
      "Employee Management API",
      "Banking Backend Service",
      "Order Processing System",
      "Student Portal Backend",
      "Spring Boot CRM",
    ],
    dailyTasks: [
      "Revise one Java core concept",
      "Solve 2 Java coding problems",
      "Practice 5 Java interview questions",
      "Build one Spring Boot endpoint",
      "Review one SQL or JPA concept",
    ],
    resumeTips: [
      "Mention Java version and Spring Boot stack clearly",
      "Highlight API and database experience",
      "Add Java-based project links",
      "Show testing with JUnit or Mockito",
      "Include DSA or problem-solving strength",
      "Quantify backend performance or feature impact",
    ],
    completedRoadmapSteps: 4,
    completedTaskCount: 2,
    confidence: "Building",
    practicedQuestions: 6,
    resumeScore: 82,
    atsFriendly: "Good",
    missingSections: ["Testing highlights", "Architecture impact"],
    interviewSuggestion: "Explain OOP, Spring Boot flow, and collections with clean examples.",
    resumeSuggestion: "Anchor your resume around Java projects with APIs, DB work, and testing.",
  },
  "Data Analyst": {
    roadmap: [
      "Spreadsheet fundamentals",
      "SQL querying",
      "Data cleaning techniques",
      "Descriptive statistics",
      "Python for analysis",
      "Pandas and NumPy",
      "Data visualization",
      "Dashboarding in Power BI or Tableau",
      "Business case storytelling",
      "A/B testing basics",
      "Build analysis portfolios",
    ],
    skills: [
      "Excel",
      "SQL",
      "Python",
      "Pandas",
      "Power BI",
      "Tableau",
      "Data Cleaning",
      "Storytelling",
    ],
    interviewTopics: [
      "SQL aggregations",
      "Joins and subqueries",
      "Data cleaning workflow",
      "Null handling",
      "Descriptive statistics",
      "Dashboard metrics",
      "Business communication",
      "A/B testing basics",
      "Pandas operations",
      "Insight presentation",
    ],
    projects: [
      "Sales Performance Dashboard",
      "Customer Churn Analysis",
      "Job Market Trend Report",
      "E-commerce Funnel Analysis",
      "Student Placement Insights",
      "Marketing Campaign Dashboard",
    ],
    dailyTasks: [
      "Revise one SQL concept",
      "Clean one sample dataset",
      "Practice 5 analyst interview questions",
      "Create one chart or dashboard view",
      "Write one insight summary",
    ],
    resumeTips: [
      "Highlight dashboards with business outcomes",
      "Mention SQL and BI tools clearly",
      "Show data cleaning and transformation work",
      "Quantify decisions supported by your analysis",
      "Add portfolio links or case studies",
      "Emphasize stakeholder communication",
    ],
    completedRoadmapSteps: 5,
    completedTaskCount: 2,
    confidence: "Steady",
    practicedQuestions: 7,
    resumeScore: 85,
    atsFriendly: "Strong",
    missingSections: ["Portfolio links", "Outcome metrics"],
    interviewSuggestion: "Practice explaining the story behind dashboards, not just the charts.",
    resumeSuggestion: "Show measurable insights, clean visuals, and the business decisions you supported.",
  },
  "AI/ML Engineer": {
    roadmap: [
      "Python programming fundamentals",
      "Linear algebra and statistics basics",
      "Data preprocessing",
      "Machine learning fundamentals",
      "Model evaluation metrics",
      "Feature engineering",
      "Deep learning basics",
      "NLP or computer vision specialization",
      "MLOps and model deployment",
      "Experiment tracking",
      "Build end-to-end ML systems",
    ],
    skills: [
      "Python",
      "Pandas",
      "Scikit-learn",
      "TensorFlow or PyTorch",
      "Statistics",
      "Feature Engineering",
      "Model Evaluation",
      "MLOps Basics",
    ],
    interviewTopics: [
      "Bias vs variance",
      "Supervised vs unsupervised learning",
      "Feature scaling",
      "Cross validation",
      "Precision and recall",
      "Overfitting control",
      "Neural network basics",
      "NLP or CV fundamentals",
      "Model deployment tradeoffs",
      "Experiment tracking",
    ],
    projects: [
      "Resume Screening Model",
      "Job Recommendation Engine",
      "Customer Churn Predictor",
      "Sentiment Analysis App",
      "Image Classification Pipeline",
      "Forecasting Dashboard",
    ],
    dailyTasks: [
      "Revise one ML concept",
      "Run one notebook experiment",
      "Practice 5 ML interview questions",
      "Tune one model parameter",
      "Document one project insight",
    ],
    resumeTips: [
      "Mention models, datasets, and evaluation metrics",
      "Highlight deployment or inference workflows",
      "Show Python and ML library usage clearly",
      "Add GitHub or demo links for ML projects",
      "Quantify model improvements",
      "Include experimentation and iteration process",
    ],
    completedRoadmapSteps: 4,
    completedTaskCount: 2,
    confidence: "Building",
    practicedQuestions: 6,
    resumeScore: 84,
    atsFriendly: "Good",
    missingSections: ["Evaluation metrics", "Deployment details"],
    interviewSuggestion: "Be ready to justify model choice, metrics, and production tradeoffs.",
    resumeSuggestion: "Lead with real model results, datasets used, and deployment proof.",
  },
  "DevOps Engineer": {
    roadmap: [
      "Linux fundamentals",
      "Networking basics",
      "Git and collaboration workflows",
      "Scripting with Bash or Python",
      "CI/CD pipelines",
      "Docker containers",
      "Kubernetes basics",
      "Infrastructure as Code",
      "Cloud deployment workflows",
      "Monitoring and alerting",
      "DevSecOps practices",
    ],
    skills: [
      "Linux",
      "Git",
      "Docker",
      "Kubernetes",
      "CI/CD",
      "Terraform",
      "AWS or Azure Basics",
      "Monitoring",
    ],
    interviewTopics: [
      "Linux commands",
      "Networking and DNS basics",
      "CI/CD pipeline stages",
      "Docker image lifecycle",
      "Kubernetes objects",
      "Infrastructure as Code",
      "Deployment strategies",
      "Monitoring and logs",
      "Incident response basics",
      "Security in pipelines",
    ],
    projects: [
      "CI/CD Pipeline for React App",
      "Dockerized MERN Deployment",
      "Kubernetes Sample App",
      "Infrastructure as Code Setup",
      "Monitoring Stack Dashboard",
      "Blue-Green Deployment Demo",
    ],
    dailyTasks: [
      "Revise one Linux or networking concept",
      "Practice one Docker or Kubernetes task",
      "Practice 5 DevOps interview questions",
      "Improve one CI/CD workflow",
      "Document one deployment process",
    ],
    resumeTips: [
      "Highlight deployment automation work",
      "Mention Docker, Kubernetes, and CI/CD clearly",
      "Show cloud or infrastructure ownership",
      "Quantify reliability or release improvements",
      "Include monitoring and incident response tools",
      "Add Infrastructure as Code experience",
    ],
    completedRoadmapSteps: 5,
    completedTaskCount: 2,
    confidence: "Ready",
    practicedQuestions: 8,
    resumeScore: 86,
    atsFriendly: "Strong",
    missingSections: ["Cloud details", "Reliability metrics"],
    interviewSuggestion: "Explain deployment flow, rollback strategy, and monitoring decisions clearly.",
    resumeSuggestion: "Emphasize automation, stability gains, and ownership of delivery pipelines.",
  },
};
